---

- hosts: all
  become: true
  tasks:

  - name: Install httpd package
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]
