---

- hosts: all
  become: true
  tasks:

  - name: Install httpd package
    dnf:
      name: httpd
    when: ansible_distribution == "Rocky"
  
  - name: Add support for php
    dnf:
      name: php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]
