---
- hosts: all
  become: yes


  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      dnf:
        name: epel-release
        state: present
    
    - name: Import Remi GPG key.
      rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
        state: present
    
    - name: Install Remi repo
      dnf:
        name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
        state: present

    - name: Disabling firewalld
      service:
        name: firewalld
        state: stopped

    - name: Install nodejs and npm
      dnf:
        name: npm
        state: present
        enablerepo: epel

    - name: Install Forever (to run our nodejs app)
      npm:
        name: forever
        global: yes
        state: present

    - name: Ensure teh node.js app directory exists
      file:
        path: "{{ node_apps_location }}"
        state: directory
    
    - name: Copy copy node.js app to the server
      copy:
        src: app
        dest: "{{ node_apps_location }}"
    
    - name: Install app dependences defined in pacakge.json file
      npm:
        path: {{ node_apps_location }}/app
    

    - name: Check list of running node.js apps
      command: /usr/local/bin/forever list
      register: forever_list
      changed_when: false

    - name: Start our nodejs app
      command: "/usr/local/bin/foreverstart{{node_apps_location}}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location + '/app/app.js')==-1"
