---

- hosts: app_servers
  become: true
  tasks:

  - name: Install apache and php packages
    tags: always, apps
    package:
      name: 
        - "{{ php_package }}"
        - "{{ apache_package }}"
      state: latest
      update_cache: yes

  - name: Copy files to app servers
    tags: always, apps, file-copy
    copy:
      src: default_index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: Install apache and php packages
    tags: always, dbs
    package:
      name:
        - "{{ mysql_package }}"
        - "{{ mysql_server_package }}"
        - "{{ php_package }}"
        - "{{ apache_package }}"
      state: latest
      update_cache: yes
 
 

